### PR TITLE
Check duplicate and missing GTFS entity keys

### PR DESCRIPTION
**Pull request by abyrd**
Addresses #792. A method is defined and applied for all entity types with simple string IDs, including stops and routes.

### CODE REVIEW

**Review by trevorgerhardt — APPROVED** [review]
Looks good to me 👍

**Comment by abyrd** [comment]
I just made a few different defective feeds with missing and duplicate stop and route IDs. Everything works as expected, but this revealed another preexisting problem: when there are problems with references to entities like stops, later stages in the import can fail hard with null pointer exceptions. This aborts the entire import and all we see is the NPE instead of the detailed error messages. I made the pattern-finding stage of the import conditional on there being no severe errors recorded (including referential integrity). This had the intended effect: I now see detailed error messages for all the problems instead of one cryptic NPE stack trace.

I noticed that `DuplicateKeyError` has only medium severity, when it might be considered a sign of very bad input data. But this change was made in 2021, a year more recently than the rest of the file, as part of reverting some other problematic change. I'm going to assume for now that we set this to medium for a good reason (related to some real-world input files).

**Comment by abyrd** [comment]
CodeQL build is failing for the same reasons discussed at https://github.com/conveyal/r5/pull/872#issuecomment-1473656401

**Comment by abyrd** [comment]
Build problems were resolved by copying the polyline encoder v0.2 into the Conveyal Maven repo and removing the axiomalaska repo from our gradle build config.

**Review by ansoncfit — APPROVED** [review]
Thanks -- it will be helpful to see relevant error messages rather than just the NPEs at later import stages.

**Pull request merged**
