### PR TITLE
Updates Google's Java libs from v18 (released 2014) to 24 (released 2018)

### PR DESCRIPTION
**Pull request by trevorgerhardt**

### CODE REVIEW

**Comment by trevorgerhardt** [comment]
Comparing Guava's `LittleEndianDataOutputStream` to r5's `LittleEndianIntOutputStream` gave the following results:

Run 1:
```
16:44:55.344 [qtp1476296711-36] INFO  c.c.r.a.cluster.GridResultAssembler - Writing travel time surface of size 370300 kB
16:44:59.076 [qtp1476296711-36] INFO  c.c.r5.analyst.cluster.AnalystWorker - Internal stream took 3732 ms
16:44:59.076 [qtp1476296711-36] INFO  c.c.r.a.cluster.GridResultAssembler - Writing travel time surface of size 370300 kB
16:45:03.741 [qtp1476296711-36] INFO  c.c.r5.analyst.cluster.AnalystWorker - Guava stream took 4665 ms
```

Run 1:
```
16:48:26.403 [qtp1476296711-34] INFO  c.c.r.a.cluster.GridResultAssembler - Writing travel time surface of size 370300 kB
16:48:33.282 [qtp1476296711-34] INFO  c.c.r5.analyst.cluster.AnalystWorker - Internal stream took 6879 ms
16:48:33.282 [qtp1476296711-34] INFO  c.c.r.a.cluster.GridResultAssembler - Writing travel time surface of size 370300 kB
16:48:39.984 [qtp1476296711-34] INFO  c.c.r5.analyst.cluster.AnalystWorker - Guava stream took 6702 ms
```

No noticeable difference for 370mb files. Might attempt with a gig and see how that rolls.

**Comment by abyrd** [comment]
The above speed measurements are for new v24 Guava and our custom little-endian int output. So we know that current v24 Guava is as fast as our custom implementation. We should also compare with the old v18 Guava we were using before just to know whether there was indeed a bugfix or change that made v24 faster than v18.

Also, these tests were run only twice which is not enough for JIT to kick in, and not enough to see GC variation. We need to run this comparison in a loop for many iterations - @trevorgerhardt is now doing this.

**Comment by trevorgerhardt** [comment]
Switched to v18.0 and ran it over a loop to see if there were any JIT optimizations:

```
17:27:05.827 [qtp1826061363-31] INFO  c.c.r.a.cluster.GridResultAssembler - Writing travel time surface of size 370300 kB
17:27:08.628 [qtp1826061363-31] INFO  c.c.r5.analyst.cluster.AnalystWorker - Internal stream run 2800 ms, avg 3068 ms
17:27:08.629 [qtp1826061363-31] INFO  c.c.r.a.cluster.GridResultAssembler - Writing travel time surface of size 370300 kB
17:27:10.065 [WORKER 2f4f20d05a4c473890529d1371edac6b] INFO  c.c.r5.analyst.cluster.AnalystWorker - Polling the broker did not yield any regional tasks. Sleeping 10 sec.
17:27:13.619 [qtp1826061363-31] INFO  c.c.r5.analyst.cluster.AnalystWorker - Guava stream run 4987 ms, avg 5076 ms
17:27:13.619 [qtp1826061363-31] INFO  c.c.r.a.cluster.GridResultAssembler - Writing travel time surface of size 370300 kB
17:27:18.021 [qtp1826061363-31] INFO  c.c.r5.analyst.cluster.AnalystWorker - Internal stream run 4402 ms, avg 3097 ms
17:27:18.021 [qtp1826061363-31] INFO  c.c.r.a.cluster.GridResultAssembler - Writing travel time surface of size 370300 kB
17:27:20.077 [WORKER 2f4f20d05a4c473890529d1371edac6b] INFO  c.c.r5.analyst.cluster.AnalystWorker - Polling the broker did not yield any regional tasks. Sleeping 10 sec.
17:27:23.478 [qtp1826061363-31] INFO  c.c.r5.analyst.cluster.AnalystWorker - Guava stream run 5457 ms, avg 5084 ms
17:27:23.478 [qtp1826061363-31] INFO  c.c.r.a.cluster.GridResultAssembler - Writing travel time surface of size 370300 kB
17:27:27.008 [qtp1826061363-31] INFO  c.c.r5.analyst.cluster.AnalystWorker - Internal stream run 3529 ms, avg 3106 ms
17:27:27.008 [qtp1826061363-31] INFO  c.c.r.a.cluster.GridResultAssembler - Writing travel time surface of size 370300 kB
17:27:30.091 [WORKER 2f4f20d05a4c473890529d1371edac6b] INFO  c.c.r5.analyst.cluster.AnalystWorker - Polling the broker did not yield any regional tasks. Sleeping 10 sec.
17:27:32.646 [qtp1826061363-31] INFO  c.c.r5.analyst.cluster.AnalystWorker - Guava stream run 5638 ms, avg 5096 ms
17:27:32.646 [qtp1826061363-31] INFO  c.c.r.a.cluster.GridResultAssembler - Writing travel time surface of size 370300 kB
17:27:37.671 [qtp1826061363-31] INFO  c.c.r5.analyst.cluster.AnalystWorker - Internal stream run 5024 ms, avg 3146 ms
```
After 25+ runs average appeared to be 3.1s for internal style and 5s for guava

**Comment by abyrd** [comment]
Our conclusion here is that, for some reason not apparent from the code itself, our implementation is over 35% faster than the Guava one, but the old Guava v18 is not measurably slower than the new Guava v24. These differences are only apparent though on these huge files that are hundreds of MB or even multiple GB. In practice these grids are returned over HTTP to a web client or saved in very large numbers on S3 for quick retrieval by a web client. They cannot be huge, we need to limit them to a few MB gzipped.

So we're going to have to consider this a mostly unsolved mystery, and our approach to avoiding the problem is just limiting the size of the files to be written. Given that the files will be small, we will avoid NIH syndrome and use standard implementations from libraries - LittleEndianDataOutputStream from Guava, but also the S3 upload manager class from newer AWS SDKs.

**Comment by abyrd** [comment]
We're going to update Guava anyway, since the one we're using is so old. This does mean we should start updating Guava in other projects though to avoid builds with multiple conflicting versions of Guava.

**Pull request merged**
