### PR TITLE
Json config support

### PR DESCRIPTION
**Pull request by buma**
This branch adds:
- debug client which can show speeds, flags, permission, traffic signals
- debug client which shows point to point paths and full state tree
- support for permissions on streets
- support for speeds on streets
- support for jsonConfig
- support for walking with bike
- preliminary point to point API
- time and weight separation in states

It would be great if this changes would be tested in other R5 entry points:
- worker
- static
- static-server

Nothing should break.

### CODE REVIEW

**Comment by abyrd** [comment]
Hi @buma, I'm preparing to merge this. I see that in a diff of this PR against master, some commits and code from @mattwigway are present. For example, LTSRelabeler.java. Can you clarify for me why this PR includes commits from @mattwigway? I'm just wondering if this is intentional or we've got accidental divergence in branches here.

**Comment by buma** [comment]
Hello @abyrd, this is @mattwigway's https://github.com/conveyal/r5/tree/jsonConfig-matt branch which diverged from mine. It adds bike walking and some other labeling stuff.

When we talk about merging It was said that we need to first merge matt's branch with mine and then everything with master since that was the order of divergence.

**Comment by abyrd** [comment]
Thanks @buma. So to confirm, all the commits I see here are intentional and reflect the current state of Matt's work?

**Comment by abyrd** [comment]
I just went through the commit log of his branch and see no additional commits besides the ones here, so it looks clean. Thanks for the info @buma. After this is merged I will do the gtfs-lib release and merge the Joda time removal.

**Comment by buma** [comment]
As far as I know this branch was intended to be merged to mine and master, but we can wait for Matt.

Th most problematic thing that can happen after this merge is car routing is useless when islands in graph are removed. Results can be seen in [#27](https://github.com/conveyal/r5/issues/27#issuecomment-161349176)

**Comment by abyrd** [comment]
Thanks for the warning. Defects in routing are to be expected at this stage of development, especially for the non-walking modes. My main concern was that some time has passed, so I just wanted to check that this was still current before merging. I'm reviewing currently, and will merge soon.

**Comment by mattwigway** [comment]
I believe that @buma merged my branch into his before making the pull
request.

On Mon, Dec 21, 2015 at 7:44 AM, Andrew Byrd <notifications@github.com>
wrote:

> Hi @buma <https://github.com/buma>, I'm preparing to merge this. I see
> that in a diff of this PR against master, some commits and code from
> @mattwigway <https://github.com/mattwigway> are present. For example,
> LTSRelabeler.java. Can you clarify for me why this PR includes commits from
> @mattwigway <https://github.com/mattwigway>? I'm just wondering if this
> is intentional or we've got accidental divergence in branches here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/conveyal/r5/pull/53#issuecomment-166296442>.
>



-- 
Matthew Wigginton Conway [WIG-in-tun CON-way]
Transportation Analytics/Open Source
Washington, DC

**Pull request merged**
